---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/smartmav/nelson.smartmavuno.com/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R out/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/echo "RewriteEngine On" > $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteBase /" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteRule ^index\.html$ - [L]" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteCond %{REQUEST_FILENAME} !-f" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteCond %{REQUEST_FILENAME} !-d" >> $DEPLOYPATH/.htaccess
    - /bin/echo "RewriteRule . /index.html [L]" >> $DEPLOYPATH/.htaccess