//import our Applayout component here so we use it vereywhere in our app
import Applayout from "@/src/components/layout/AppLayout";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Applayout>{children}</Applayout>
      </body>
    </html>
  );
}